config/routes.rb
Rails.application.routes.draw do

  # resources :tasks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # CREATE
  get '/tasks/new', to: 'tasks#new', as: :create

  # READ ALL
  get '/tasks', to: 'tasks#index', as: :all

  # READ INDIVIDUAL
  get '/tasks/:id', to: 'tasks#show', as: :task

  # STORE
  post '/tasks', to: 'tasks#create'

  # UPDATE
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

  # DELETE
  delete '/tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, presence: true, acceptance: { message: 'must be abided' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to all_path
  end

  def edit

  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>

<div class="form-group mb-3">
  <%= f.label(:title, class: "mb-1") %><br>
  <%= f.text_field(:title, class: "form-control", placeholder: "Insert title") %>
</div>
<div class="form-group mb-3">
  <%= f.label(:details, class: "mb-1") %>
  <%= f.text_area(:details, class: "form-control", placeholder: "Insert details", rows: "6") %>
</div>
<div class="form-group mb-3">
  <%= f.check_box :completed %>
  <%= f.label "Mark as complete" %>
</div>
  <%= f.submit(class: "btn-primary btn") %>
  <%= link_to "Cancel", all_path, class: "btn-outline-secondary btn" %>

<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="my-5">Edit Task</h1>
  <div class="d-flex flex-column flex-md-row my-3 align-items-center justify-content-center">
    <div class="list-group w-100">

    <%= render 'form', task: @task %>

</div>
</div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-5">My Tasks</h1>
  <% @tasks.each do |task| %>
  <div class="d-flex flex-column flex-md-row my-3 align-items-center justify-content-center">
    <div class="list-group w-100">
      <label class="list-group-item d-flex gap-3 p-3">
        <input class="form-check-input flex-shrink-0" <%= task.completed == true ? "checked" : "" %> type="checkbox" style="font-size: 1.375em;">
        <span class="pt-1 form-checked-content">
          <strong><%= task.title %></strong>
          <span class="delete">
            <%= link_to "🗑️",
            task_path(task.id),
            data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure you want to delete #{task.title}?"
            } %>
          </span>
          <small class="d-block text-body-secondary">
            <%= link_to "View task details", task_path(task.id) %>
          </small>
        </span>
      </label>
    </div>
  </div>
  <% end %>
  <%= link_to "Add a new task", create_path, class: "btn-primary btn mt-4" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="my-5">Add Task</h1>
    <div class="d-flex flex-column flex-md-row my-3 align-items-center justify-content-center">
      <div class="list-group w-100">

    <%= render 'form', task: @task %>

    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="my-5">My Task</h1>
  <div class="d-flex flex-column flex-md-row my-3 align-items-center justify-content-center">
    <div class="list-group w-100">
      <label class="list-group-item d-flex gap-3 p-3">
        <span class="pt-1 form-checked-content">
          <h3><%= @task.title %></h3>
          <small class="d-block text-body-secondary">
            <%= @task.details %>
          </small>
        </span>
      </label>
    </div>
  </div>
  <%= link_to "Edit task", edit_path, class: "btn-primary btn mt-4" %>
  <%= link_to "Show all", all_path, class: "btn-outline-secondary btn mt-4" %>
</div>